#!/bin/env bash

# socat \
	# UNIX-LISTEN:"$(gpgconf --list-dir agent-socket)",fork, \
	# EXEC:'wsl-relay.exe --input-closes --pipe-closes --gpg',nofork &

socat \
	UNIX-LISTEN:"$(gpgconf --list-dir agent-ssh-socket)",fork, \
	EXEC:'wsl-relay.exe --input-closes --pipe-closes -v --gpg S.gpg-agent.ssh',nofork &

wait
